import {useEffect,useState} from 'react';import {Config,Diagnostics,unwrap} from './types';
type Props={config:Config;models:string[];save:(c:Config)=>Promise<void>;refresh:()=>void};
export function Settings({config,models,save,refresh}:Props){
 const [draft,setDraft]=useState(config),[section,setSection]=useState('GENERAL'),[error,setError]=useState(''),[saved,setSaved]=useState(false),[devices,setDevices]=useState<MediaDeviceInfo[]>([]);
 useEffect(()=>setDraft(config),[config]);const update=(key:keyof Config,value:unknown)=>{setDraft(d=>({...d,[key]:value}));setSaved(false)};
 const toggle=(key:keyof Config,label:string,help?:string)=><label className="setting-row"><span>{label}<small>{help}</small></span><input type="checkbox" checked={Boolean(draft[key])} onChange={e=>update(key,e.target.checked)}/></label>;
 const input=(key:keyof Config,label:string,type='text',min?:number,max?:number)=><label className="setting-row"><span>{label}</span><input type={type} value={String(draft[key])} min={min} max={max} step={key==='temperature'||key==='frameThreshold'||key==='speechSpeed'||key==='speechVolume'?.01:1} onChange={e=>update(key,type==='number'?Number(e.target.value):e.target.value)}/></label>;
 const select=(key:keyof Config,label:string,choices:string[])=><label className="setting-row"><span>{label}</span><select value={String(draft[key])} onChange={e=>update(key,e.target.value)}>{choices.map(v=><option key={v} value={v}>{v||'Select a model'}</option>)}</select></label>;
 const chooseRoot=async()=>{try{const p=await unwrap(window.jarvis!.selectRoot());if(p)update('fileRoot',p)}catch(e){setError(String(e))}};
 return <div className="settings-layout"><aside className="subnav">{['GENERAL','AI','VOICE','VISION','AUTOMATION','PRIVACY','SAFETY'].map(s=><button className={section===s?'active':''} key={s} onClick={()=>setSection(s)}>{s}</button>)}</aside><div className="settings-content"><div className="section-heading"><span>{section} CONFIGURATION</span><small>LOCAL SETTINGS / PERSISTENT</small></div>
 {section==='GENERAL'&&<>{toggle('startup','Launch with Windows')}{toggle('tray','Minimize to system tray')}{toggle('minimized','Start minimized')}{select('animations','Animation intensity',['full','reduced','off'])}</>}
 {section==='AI'&&<>{input('ollamaUrl','Local Ollama URL')}{select('model','Conversation model',['',...models])}{select('visionModel','Vision model',['',...models])}<button onClick={refresh}>REFRESH INSTALLED MODELS</button>{input('temperature','Temperature','number',0,2)}{input('context','Context length','number',1024,131072)}<p className="help">Choose a model with tool support for PC tasks and a vision-capable model for screen analysis. Models are never downloaded automatically.</p></>}
 {section==='VOICE'&&<>{toggle('microphone','Enable microphone','Permission is requested only when listening starts.')}{input('pythonPath','Python executable path')}{select('sttModel','Local Whisper model',['tiny','base','small','medium','large-v3','distil-large-v3'])}<label className="setting-row"><span>Microphone</span><select value={draft.microphoneId} onChange={e=>update('microphoneId',e.target.value)}><option value="">System default</option>{devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||d.deviceId}</option>)}</select></label><button onClick={()=>navigator.mediaDevices.enumerateDevices().then(d=>setDevices(d.filter(x=>x.kind==='audioinput'))).catch(e=>setError(String(e)))}>REFRESH MICROPHONES</button>{toggle('wakeEnabled','Optional wake phrase','Uses local transcription of 5-second chunks; higher CPU use and latency.')}{input('wakeWord','Wake phrase')}{input('ptt','Push-to-talk shortcut')}{toggle('tts','Speak responses with local Windows voices')}{input('speechSpeed','Speech speed','number',.5,2)}{input('speechVolume','Speech volume','number',0,1)}</>}
 {section==='VISION'&&<>{select('vision','Screen privacy mode',['off','manual','awake','continuous'])}{input('monitor','Monitor ID (blank = primary)')}{input('interval','Minimum analysis interval / seconds','number',10,300)}{input('imageQuality','Capture width / pixels','number',400,1920)}{input('frameThreshold','Frame difference threshold','number',0,1)}<p className="help">Screenshots stay in memory. Continuous vision compares downsampled frames before inference. OCR and active-window-only capture are not included in this release.</p></>}
 {section==='AUTOMATION'&&<>{toggle('mock','Mock mode','All PC input and file mutations are simulated.')}{toggle('mouse','Allow mouse control')}{toggle('keyboard','Allow keyboard control')}{toggle('browser','Allow app and browser launch')}{toggle('filesystem','Allow filesystem tools')}{input('fileRoot','Allowed filesystem root')}<button onClick={()=>void chooseRoot()}>CHOOSE FILE ROOT</button>{toggle('powershell','Allow read-only PowerShell','Only Get-Date, Get-ComputerInfo and Get-PSDrive are allowlisted.')}</>}
 {section==='PRIVACY'&&<>{toggle('microphone','Microphone access')}{toggle('memory','Explicit local memory')}<p className="help">Conversation text, screenshots, clipboard contents and tool arguments are never written to audit logs. Memories are saved only through the Memory page. SQLite is local and unencrypted.</p></>}
 {section==='SAFETY'&&<><div className="risk-list"><p><b>00 / SAFE</b> System readings and responses.</p><p><b>01 / NORMAL</b> Allowlisted app launch and navigation.</p><p><b>02 / IMPORTANT</b> Exact-action approval for clicks, keystrokes, clipboard, file moves, and form submission.</p><p><b>03 / CRITICAL</b> Explicit approval for deletion and restricted PowerShell.</p></div><p className="help">The model cannot disable safety. Approvals expire after 60 seconds and apply to one action. Permanent deletion, elevated commands, registry edits, installers and arbitrary executable launch are blocked.</p><p className="danger-text">EMERGENCY STOP: CTRL + SHIFT + ESCAPE<br/>PyAutoGUI also stops when the pointer reaches a screen corner.</p></>}
 <div className="settings-save"><button className="primary" onClick={async()=>{try{await save(draft);setSaved(true);setError('')}catch(e){setError(String(e))}}}>SAVE CONFIGURATION</button>{saved&&<span>CONFIGURATION SAVED</span>}{error&&<p role="alert">{error}</p>}</div></div></div>
}
export function Setup({config,save,close}:{config:Config;save:(c:Config)=>Promise<void>;close:()=>void}){
 const [checks,setChecks]=useState<Diagnostics|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);try{setChecks(await unwrap(window.jarvis!.diagnostics()));setError('')}catch(e){setError(String(e))}finally{setBusy(false)}};
 useEffect(()=>{void run()},[]);
 return <div className="modal-shade"><section className="setup-modal" role="dialog" aria-modal="true" aria-labelledby="setup-title"><span className="eyebrow">INITIALIZATION PROTOCOL / 01</span><h1 id="setup-title">Welcome to JARVIS.</h1><p>Your assistant runs locally. Begin with mock automation and enable each capability when you’re ready.</p><div className="setup-checks">{[['Windows desktop',checks?.windows],['Python executable',checks?.python],['Local speech recognition',checks?.stt],['Mouse / keyboard worker',checks?.automation],['Ollama service',checks?.ollama],['Installed AI models',Boolean(checks?.models.length)],['Connected displays',Boolean(checks?.monitors.length)]].map(([label,ok])=><div key={String(label)}><span>{label}</span><b className={ok?'good':'warning'}>{checks?ok?'READY':'NOT CONFIGURED':'CHECKING'}</b></div>)}</div><p className="help">Install Ollama separately and select your models in Settings. For speech and PC input, install voice/requirements.txt into a Python environment and set its executable path. No paid API is required.</p>{error&&<p role="alert">{error}</p>}<footer><button disabled={busy} onClick={()=>void run()}>RECHECK</button><button className="primary" onClick={async()=>{await save({...config,setupComplete:true});close()}}>ENTER COMMAND CENTER →</button></footer></section></div>
}
